"""Added account id to user table

Revision ID: 03e51b3b3ede
Revises: 5fc1a03ad0a7
Create Date: 2025-06-11 13:54:17.357330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e51b3b3ede'
down_revision: Union[str, None] = '5fc1a03ad0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_column('users', 'account_id')
    # ### end Alembic commands ###
