"""Added query_template_assignment_id column in AthenaQueryExecution table

Revision ID: 4693d7e72a71
Revises: b418df217fab
Create Date: 2025-05-19 02:21:15.000908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4693d7e72a71'
down_revision: Union[str, None] = 'b418df217fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athena_query_executions', sa.Column('query_template_assignment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athena_query_executions', 'query_template_assignment_id')
    # ### end Alembic commands ###
