"""Removed unique from name and added unique constraints on User Settings table

Revision ID: b418df217fab
Revises: a91aa25dd787
Create Date: 2025-05-19 00:31:33.665641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b418df217fab'
down_revision: Union[str, None] = 'a91aa25dd787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_settings_name_key', 'user_settings', type_='unique')
    op.create_unique_constraint('uix_user_settings_name_user_id', 'user_settings', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_settings_name_user_id', 'user_settings', type_='unique')
    op.create_unique_constraint('user_settings_name_key', 'user_settings', ['name'])
    # ### end Alembic commands ###
