"""Added cost_optimization id

Revision ID: 675956ac17c7
Revises: 8c02d519d115
Create Date: 2025-06-21 20:30:10.722847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675956ac17c7'
down_revision: Union[str, None] = '8c02d519d115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_owner', sa.Column('cost_optimize_id', sa.Integer(), nullable=True))
    op.add_column('resource_owner', sa.Column('account_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_owner', 'account_id')
    op.drop_column('resource_owner', 'cost_optimize_id')
    # ### end Alembic commands ###
