"""Resource Owner Table

Revision ID: 9ef423e45304
Revises:
Create Date: 2025-06-17 16:06:09.540470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9ef423e45304"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_owner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.String(length=200), nullable=True),
        sa.Column("owner_name", sa.String(length=200), nullable=True),
        sa.Column("owner_email", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "TODO", "WIP", "COMPLETED", "SUPRESSED", name="resourceownerstatus"
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource_owner")
    # ### end Alembic commands ###
