"""Removed cost optimization id

Revision ID: e733d161a2c5
Revises: 675956ac17c7
Create Date: 2025-06-26 22:32:06.056032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e733d161a2c5'
down_revision: Union[str, None] = '675956ac17c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_owner', 'cost_optimize_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_owner', sa.Column('cost_optimize_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
